http:
  middlewares:
    default-security-headers:
      headers:
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: no-referrer-when-downgrade
        customFrameOptionsValue: SAMEORIGIN
    gzip-compress:
      compress: {}
    rate-limit-default:
      rateLimit:
        average: 100
        burst: 50
    global-chain:
      chain:
        middlewares:
          - gzip-compress
          - default-security-headers
          - rate-limit-default
    dashboard-auth:
      basicAuth:
        usersFile: "/run/traefik/secrets/dashboard-users"
    dashboard-chain:
      chain:
        middlewares:
          - dashboard-auth
          - default-security-headers

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
