version: '3.9'

services:
  suite-login:
    build:
      context: ../../../
      dockerfile: cp/suite-login/Dockerfile
    container_name: genius-suite-login
    restart: always
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: suite-login
      NODE_ENV: development
    ports:
      - "3003:3003"
    networks:
      - observability
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://0.0.0.0:3003/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

networks:
  observability:
    external: true
    name: geniuserp_observability
